// Code généré automatiquement. Ne pas modifier.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Bombix":return img`
................................
................................
................................
................................
................................
................................
................................
................................
.................e..............
................ee..............
...............ee...............
..............ee................
..............e.................
..............e.................
...........fffffff..............
..........fffffffff.............
.........fffffffffff............
........ff1f1fff1f1ff...........
........fff1fffff1fff...........
........ff1f1fff1f1ff...........
........fffffffffffff...........
........fffffffffffff...........
........fffff111fffff...........
.........fff1fff1fff............
..........fffffffff.............
...........fffffff..............
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Code généré automatiquement. Ne pas modifier.
